/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Persistencia;
import static Vista.TallerDeMecanicaApp.op;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Astrid
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    VentanaMecanico mecanico;
    VentanaReportes reporte;
    VentanaProveedores prov;
    VentanaFacturacion fact;
    public static boolean archivo;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        
       
        mecanico = new VentanaMecanico(null,true);
        mecanico.setLocationRelativeTo(null);
        reporte = new VentanaReportes(null,true);
        reporte.setLocationRelativeTo(null);
        prov = new VentanaProveedores(null,true);
        prov.setLocationRelativeTo(null);
        fact = new VentanaFacturacion(null,true);
        fact.setLocationRelativeTo(null);
        archivo = true;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/66.png")).getImage());
        modificarBotones();
//        if(Persistencia.leerContacto()!=null){
//        op = Persistencia.leerContacto();
//       /// JOptionPane.showMessageDialog(null, "Archivo Cargado");
//        }
//        else JOptionPane.showMessageDialog(null, "Archivo NO Cargado");
         this.setLocationRelativeTo(null);
        cerrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarCambios = new javax.swing.JButton();
        btnMecanico = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AServices");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 160, 50));

        btnMecanico.setText("Gestion de Trabajos");
        btnMecanico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMecanicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 49));

        btnReportes.setText("Listas Trabajos y Clientes");
        btnReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 49));

        btnFacturacion.setText("Facturacion");
        btnFacturacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 50));

        btnProveedores.setText("Inventario");
        btnProveedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 50));

        btnManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda.png"))); // NOI18N
        btnManual.setToolTipText("Acerca de");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        getContentPane().add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 38, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/66.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-azul-industrial.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
       prov.llenarTabla();
        prov.setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMecanicoActionPerformed
        // TODO add your handling code here:
        mecanico.setVisible(true);
    }//GEN-LAST:event_btnMecanicoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        reporte.llenarTablas();
        reporte.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        Persistencia.escribirContacto(op);
        archivo = true;
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        fact.setVisible(true);
    }//GEN-LAST:event_btnFacturacionActionPerformed

    /// https://contrespace.wordpress.com/2010/12/30/abrir-pdf-en-java/
    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"Manual.pdf");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al Abrir el Archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnManualActionPerformed

    public void cerrar() {
        try {
            /*confirmacion de salida*/
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener( new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
           this.setVisible(true);//hacemos visible el frame
        }catch (Exception e) {
//            e.printStackTrace();
        }
    }
    
    public void confirmarSalida(){
       if(archivo==false){ 
        int i =JOptionPane.showConfirmDialog(this,"¿Desea guardar Cambios realizados?","Confirmar Salida",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(i==0){
            Persistencia.escribirContacto(op);
            System.exit(0);  
          }else{
         System.exit(0); 
        }
       }else{
        System.exit(0); 
       }
    }
     public void modificarBotones(){
        btnManual.setBorderPainted(false);
        btnManual.setContentAreaFilled(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnMecanico;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
