/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Material;
import Logica.Proveedores;
import static Vista.TallerDeMecanicaApp.op;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Astrid
 */
public class VentanaProveedores extends javax.swing.JDialog {
    
    ArrayList<Material> material = new ArrayList<Material>();
      /////////////// PARA LA TABLA DE PROVEEDORES  ////////////////////////////////////////////
     String titulo[]={"Codigo","Descripcion del Proveedor","Fax","Pais"};
     Object datos[][];
     DefaultTableModel modelo ;
      /////////////// PARA LA TABLA DE PROVEEDORES ////////////////////////////////////////////
     
     /////////////// PARA LA TABLA DE INVENTARIO  ////////////////////////////////////////////
     String tituloMateriales[]={"Numero","Descripcion del Material","Cantidad de Material","Precio del Material"};
     Object datosMateriales[][];
     DefaultTableModel modeloMateriales ;
      /////////////// PARA LA TABLA DE INVENTARIO  ////////////////////////////////////////////
    /**
     * Creates new form VentanaProveedores
     */
    public VentanaProveedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
        
        modelo =  new DefaultTableModel(datos,titulo);
        tablaProveedores.setModel(modelo);
        
        modeloMateriales =  new DefaultTableModel(datosMateriales,tituloMateriales);
        tablaInventario.setModel(modeloMateriales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProveedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnPedidoProveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proveedores");
        setResizable(false);

        panelProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Listado Proveedores", 0, 0, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProveedores);

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Materiales en cero", 0, 0, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaInventario);

        btnPedidoProveedor.setText("Pedir a Proveedor");
        btnPedidoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoProveedorActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad a pedir: ");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPedidoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedidoProveedor)
                    .addComponent(jLabel1)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPedidos.setText("Mostrar materiales acabados");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPedidos)
                    .addComponent(panelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidos)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        llenarTablaInventario();
        
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnPedidoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoProveedorActionPerformed
        // TODO add your handling code here:
        try{
        int a = tablaInventario.getSelectedRow();
        int cant= Integer.parseInt(txtCantidad.getText());
        int cantidad = Integer.parseInt((String) tablaInventario.getValueAt(a,0));
        
        op.getMaterialesPredeterminados().get(cantidad).setCantidad(cant);
        
        System.out.println("cantidad del material"+ op.getMaterialesPredeterminados().get(0).getCantidad());
        JOptionPane.showMessageDialog(null,"Se ha Abastecido de materiales el taller. ");
        VentanaPrincipal.archivo = false;
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"No has seleccionado material","Advertencia",JOptionPane.WARNING_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"No ha ingresado los datos correctamente","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPedidoProveedorActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    public void llenarTabla(){
    ///////////// LIMPIAR LA TABLA DE PROVEEDORES  
     while(modelo.getRowCount()>0)
            modelo.removeRow(0);
    /////////////// LIMPIAR LA TABLA DE PROVEEDORES
    
    
     
     for(int i=0;i<op.getMaterialesPredeterminados().size();i++){
	for(int j=0;j<op.getMaterialesPredeterminados().get(i).getProveedores().size();j++){
                  
            
                  
		if(!comprobarRepetido(op.getMaterialesPredeterminados().get(i).getProveedores().get(j).getNombre())){
			String nombre = op.getMaterialesPredeterminados().get(i).getProveedores().get(j).getNombre();
                        String codigo = op.getMaterialesPredeterminados().get(i).getProveedores().get(j).getCodigo();
                        String fax = op.getMaterialesPredeterminados().get(i).getProveedores().get(j).getFax();
                        String pais = op.getMaterialesPredeterminados().get(i).getProveedores().get(j).getPais();
//                        material = pedido.getmMaterialesProveedor(codigo);
//                        pedido.llenarTabla(material);
                    String datos2[]={nombre,codigo,fax,pais};
                    modelo.addRow(datos2);
		}
	}
}
    }
    
    public void llenarTablaInventario(){
    
     ///////////// LIMPIAR LA TABLA DE INVENTARIO  
     while(modeloMateriales.getRowCount()>0)
            modeloMateriales.removeRow(0);
    /////////////// LIMPIAR LA TABLA DE INVENTARIO
     
     //////////// LLENANDO LA TABLA DE Materiales //////////////////
     for(int i=0;i<op.getMaterialesPredeterminados().size();i++){
         
       if(op.getMaterialesPredeterminados().get(i).getCantidad()==0){
        String numero = ""+i;
        String nombre= op.getMaterialesPredeterminados().get(i).getNombre();
        String cantidad= ""+op.getMaterialesPredeterminados().get(i).getCantidad();
        String precio= ""+op.getMaterialesPredeterminados().get(i).getPrecio();
         String datos3[]={numero,nombre,cantidad,precio};
         modeloMateriales.addRow(datos3);
       }
    }
    }
    
    public boolean comprobarRepetido(String nombre){
        for(int i=0; i<tablaProveedores.getRowCount(); i++){
            try{
            String nombreProveedor = (String)tablaProveedores.getValueAt(i,0);
            if(nombreProveedor.equals(nombre))
                return true;
            }catch(NullPointerException e){
            
            }catch(NumberFormatException e){}
        }
        return false;
    
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaProveedores dialog = new VentanaProveedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedidoProveedor;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
