/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Material;
import Logica.Persistencia;
import Logica.Proveedores;
import static Vista.TallerDeMecanicaApp.op;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Astrid
 */

/////////////////// COLOCAR BLOQUES TRY CATCH!!!!!!!!!!!!! //////////////////////////////////////
public class VentanaModificar extends javax.swing.JDialog {

    /////// DATOS PARA LA TABLA DE CLIENTES -- MODIFICAR DATOS ----  //////////
    String titulo[]={"Nombre","Identificacion","Dirección","Telefono","Cargo","Matricula Vehiculo"};
    Object datos[][];
    DefaultTableModel modelo ;
    
    /////// DATOS PARA LA TABLA DE CLIENTES -- MODIFICAR DATOS ----  //////////
    
    /////// DATOS PARA LA TABLA DE MATERIALES -- MODIFICAR DATOS- AGREGAR Y ELIMINAR MATERIALEES  ----  //////////
    String tituloTabla2[] = {"Descripcion","Cantidad","Precio"};
    Object datosTabla2[][];
    DefaultTableModel modeloTabla2;
    /////// DATOS PARA LA TABLA DE MATERIALES -- MODIFICAR DATOS- AGREGAR Y ELIMINAR MATERIALEES  ----  //////////
    
    /////// DATOS PARA LA TABLA DE MATERIALES -- AGREGAR MATERIAL A LOS TRABAJOS  ----  //////////
    String tituloTabla3[] = {"Descripcion","Cantidad","Precio"};
    Object datosTabla3[][];
     DefaultTableModel modeloTabla3;
    /////// DATOS PARA LA TABLA DE MATERIALES -- AGREGAR MATERIAL A LOS TRABAJOS  ----  //////////
     
     ////////// DATOS PARA LA TABLA DE TRABAJOS EN REVISION /////////////////
     String tituloTabla4[] = {"Codigo del Trabajo","Matricula del Vehiculo", "Nombre del Cliente", "Identificacion del Cliente"};
     Object datosTabla4[][];
     DefaultTableModel modeloTabla4;
     
     
     String nombreProv = ""; String cod = "";  String fax = ""; String pais = "";
    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cerrar();
        //// Para la tabla de modificar Datos de Clientes ////////////
        modelo =  new DefaultTableModel(datos,titulo);
        tablaClientes.setModel(modelo);
        
      //// Para la tabla de modificar Datos de Clientes ////////////
        
        //// Para la tabla de Modificar Materiales  ////////////
        modeloTabla2 = new DefaultTableModel(datosTabla2,tituloTabla2);
        tablaMateriales.setModel(modeloTabla2);
        /////// Para la tabla de Modificar Materiales  ////////////   
       
        ///// PARA LA TABLA DE AGREGAR MATERIALES AL TRABAJO  ///////////
        modeloTabla3 = new DefaultTableModel(datosTabla3,tituloTabla3);
        tablaMaterial.setModel(modeloTabla3);
        //// PARA LA TABLA DE AGREGAR MATERIALES AL TRABAJO  ///////////
        
        ////// PARA LA TABLA DE TRABAJOS EN REVISION //////////
        modeloTabla4 = new DefaultTableModel(datosTabla4,tituloTabla4);
        tablaTrabajosRevision.setModel(modeloTabla4);
        
        modificar(panelAgregarMaterial,false);
        modificar(panelAumentarHoras,false);
        modificar(panelModificarDatos,false);
    }
    
   public void modificar(JPanel panel, boolean b) {
            panel.setEnabled(b);
            for (int i = 0; i < panel.getComponentCount(); i++) {
                panel.getComponent(i).setEnabled(b);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAgregarMaterial = new javax.swing.JDialog();
        btnAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtnombreMa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioMa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantidadMa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNombreDelProveedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFaxProveedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCodigoProveedores = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPaisProveedor = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelModificarTrabajo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboAccion = new javax.swing.JComboBox();
        panelAumentarHoras = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreAumentar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoAumentar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatriculaAumentar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHorasAumentar = new javax.swing.JTextField();
        btnAumentarHoras = new javax.swing.JButton();
        panelAgregarMaterial = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreMaterial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoMaterial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMatriculaMaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterial = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarMaterial = new javax.swing.JButton();
        panelModificarDatos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnGuardarCambios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMateriales = new javax.swing.JTable();
        btnAgregarMateriales = new javax.swing.JButton();
        btnGuardarCambiosMateriales = new javax.swing.JButton();
        btnEliminarMaterial = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelDiagnostico = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoDelTrabajo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtMAtriculaDelVehiculo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNombredelCLiente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIdentificacionCliente = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        textDiagnostico = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        btnAgregarDiagnostico = new javax.swing.JButton();
        listaRevision = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaTrabajosRevision = new javax.swing.JTable();

        dialogoAgregarMaterial.setResizable(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true), "Descripcion del Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel10.setText("Descripcion del Material");

        jLabel11.setText("Precio del Material");

        txtPrecioMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioMaKeyTyped(evt);
            }
        });

        jLabel12.setText("Cantidad de materiales");

        txtCantidadMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadMaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombreMa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecioMa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadMa)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtnombreMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecioMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtCantidadMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true), "Descripcion de Proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel13.setText("Nombre del Proveedor");

        jLabel14.setText("Fax");

        jLabel15.setText("Codigo");

        jLabel16.setText("Pais");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreDelProveedor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaisProveedor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtFaxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoProveedores)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombreDelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFaxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtCodigoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPaisProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoAgregarMaterialLayout = new javax.swing.GroupLayout(dialogoAgregarMaterial.getContentPane());
        dialogoAgregarMaterial.getContentPane().setLayout(dialogoAgregarMaterialLayout);
        dialogoAgregarMaterialLayout.setHorizontalGroup(
            dialogoAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAgregarMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAgregarMaterialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogoAgregarMaterialLayout.setVerticalGroup(
            dialogoAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAgregarMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Que desea realizar: ");

        comboAccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Aumentar horas", "Agregar material", "Modificar datos" }));
        comboAccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAccionItemStateChanged(evt);
            }
        });

        panelAumentarHoras.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Aumentar horas de un trabajo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel2.setText("Nombre del cliente:");

        txtNombreAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAumentarActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo del Trabajo");

        jLabel4.setText("Matricula del Vehiculo");

        jLabel5.setText("Nuimero de horas a aumentar");

        txtHorasAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasAumentarActionPerformed(evt);
            }
        });
        txtHorasAumentar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasAumentarKeyTyped(evt);
            }
        });

        btnAumentarHoras.setText("Aumentar Horas");
        btnAumentarHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAumentarHorasLayout = new javax.swing.GroupLayout(panelAumentarHoras);
        panelAumentarHoras.setLayout(panelAumentarHorasLayout);
        panelAumentarHorasLayout.setHorizontalGroup(
            panelAumentarHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAumentarHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAumentarHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAumentarHorasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMatriculaAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHorasAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAumentarHorasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAumentarHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoAumentar)
                    .addGroup(panelAumentarHorasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAumentarHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAumentarHorasLayout.setVerticalGroup(
            panelAumentarHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAumentarHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAumentarHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAumentarHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatriculaAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtHorasAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAumentarHoras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAgregarMaterial.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Agregar Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel6.setText("Nombre del Cliente:");

        jLabel7.setText("Codigo del Trabajo");

        jLabel8.setText("Matricula del Vehiculo");

        tablaMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMaterial);
        if (tablaMaterial.getColumnModel().getColumnCount() > 0) {
            tablaMaterial.getColumnModel().getColumn(0).setResizable(false);
            tablaMaterial.getColumnModel().getColumn(1).setResizable(false);
            tablaMaterial.getColumnModel().getColumn(2).setResizable(false);
            tablaMaterial.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel9.setText("Cantidad");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        btnAgregarMaterial.setText("Agregar Material");
        btnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarMaterialLayout = new javax.swing.GroupLayout(panelAgregarMaterial);
        panelAgregarMaterial.setLayout(panelAgregarMaterialLayout);
        panelAgregarMaterialLayout.setHorizontalGroup(
            panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelAgregarMaterialLayout.createSequentialGroup()
                        .addGroup(panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarMaterialLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panelAgregarMaterialLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(14, 14, 14)))
                        .addGroup(panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarMaterialLayout.createSequentialGroup()
                                .addComponent(txtCodigoMaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMatriculaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreMaterial)))
                    .addGroup(panelAgregarMaterialLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarMaterial)))
                .addContainerGap())
        );
        panelAgregarMaterialLayout.setVerticalGroup(
            panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarMaterialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCodigoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMatriculaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarMaterialLayout.createSequentialGroup()
                        .addComponent(btnAgregarMaterial)
                        .addContainerGap())))
        );

        panelModificarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Modificar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarDatosLayout = new javax.swing.GroupLayout(panelModificarDatos);
        panelModificarDatos.setLayout(panelModificarDatosLayout);
        panelModificarDatosLayout.setHorizontalGroup(
            panelModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarCambios)))
                .addContainerGap())
        );
        panelModificarDatosLayout.setVerticalGroup(
            panelModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarDatosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCambios)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelModificarTrabajoLayout = new javax.swing.GroupLayout(panelModificarTrabajo);
        panelModificarTrabajo.setLayout(panelModificarTrabajoLayout);
        panelModificarTrabajoLayout.setHorizontalGroup(
            panelModificarTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAumentarHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAgregarMaterial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelModificarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModificarTrabajoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelModificarTrabajoLayout.setVerticalGroup(
            panelModificarTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAumentarHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAgregarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelModificarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Trabajos", panelModificarTrabajo);

        tablaMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaMateriales);
        if (tablaMateriales.getColumnModel().getColumnCount() > 0) {
            tablaMateriales.getColumnModel().getColumn(0).setResizable(false);
            tablaMateriales.getColumnModel().getColumn(1).setResizable(false);
            tablaMateriales.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAgregarMateriales.setText("Agregar Material");
        btnAgregarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaterialesActionPerformed(evt);
            }
        });

        btnGuardarCambiosMateriales.setText("Guardar Cambios");
        btnGuardarCambiosMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosMaterialesActionPerformed(evt);
            }
        });

        btnEliminarMaterial.setText("Eliminar Material");
        btnEliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarCambiosMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCambiosMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar lista de Materiales", jPanel2);

        panelDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Diagnostico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel17.setText("Codigo del Trabajo");

        jLabel18.setText("Matricula del Vehiculo");

        jLabel19.setText("Nombre del Cliente");

        jLabel20.setText("Identificacion del Cliente");

        textDiagnostico.setColumns(20);
        textDiagnostico.setRows(5);
        jScrollPane4.setViewportView(textDiagnostico);

        jLabel21.setText("Detalles del Diagnostico:");

        btnAgregarDiagnostico.setText("Agregar Diagnostico");
        btnAgregarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDiagnosticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDiagnosticoLayout = new javax.swing.GroupLayout(panelDiagnostico);
        panelDiagnostico.setLayout(panelDiagnosticoLayout);
        panelDiagnosticoLayout.setHorizontalGroup(
            panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDiagnosticoLayout.createSequentialGroup()
                        .addGroup(panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAgregarDiagnostico))
                            .addComponent(jScrollPane4)
                            .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                                .addGroup(panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoDelTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 81, Short.MAX_VALUE))
                                    .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombredelCLiente)))
                                .addGap(18, 18, 18)
                                .addGroup(panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMAtriculaDelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdentificacionCliente)))))
                        .addGap(18, 18, 18))))
        );
        panelDiagnosticoLayout.setVerticalGroup(
            panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCodigoDelTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtMAtriculaDelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNombredelCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarDiagnostico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaRevision.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Trabajos de Revision", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        tablaTrabajosRevision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaTrabajosRevision);

        javax.swing.GroupLayout listaRevisionLayout = new javax.swing.GroupLayout(listaRevision);
        listaRevision.setLayout(listaRevisionLayout);
        listaRevisionLayout.setHorizontalGroup(
            listaRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaRevisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        listaRevisionLayout.setVerticalGroup(
            listaRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaRevisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaRevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Especificar Diagnostico", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAumentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAumentarActionPerformed

    private void txtHorasAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasAumentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasAumentarActionPerformed

    private void comboAccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAccionItemStateChanged
        // TODO add your handling code here:
        if(comboAccion.getSelectedItem().toString().equals("Aumentar horas")){
            modificar(panelAumentarHoras,true);
            modificar(panelAgregarMaterial,false);
            modificar(panelModificarDatos,false);
        }
         if(comboAccion.getSelectedItem().toString().equals("Agregar material")){
            modificar(panelAgregarMaterial,true);
            modificar(panelAumentarHoras,false);
            modificar(panelModificarDatos,false);
        }
          if(comboAccion.getSelectedItem().toString().equals("Modificar datos")){
              modificar(panelModificarDatos,true);
              modificar(panelAgregarMaterial,false);
              modificar(panelAumentarHoras,false);
        
        }
    }//GEN-LAST:event_comboAccionItemStateChanged

    private void btnAumentarHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarHorasActionPerformed
        // TODO add your handling code here:
        
        try{
        String nombre, codigo, matricula;
        int numero;
        
        ////  SE RECOGEN LOS DATOS QUE INGRESO EL USUARIO //////
        int a=0;
        nombre = txtNombreAumentar.getText();
        codigo = txtCodigoAumentar.getText();
        matricula = txtMatriculaAumentar.getText();
        numero = Integer.parseInt(txtHorasAumentar.getText());
    ////  SE RECOGEN LOS DATOS QUE INGRESO EL USUARIO //////
        int p=0;
     
        for(int i = 0; i<op.getClientes().size(); i++){
           
           for(int j = 0; j<op.getClientes().get(i).getMecanico().size();j++){
               
               for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size(); k++){
                    // JOptionPane.showMessageDialog(null,"numero de horas "+numero);
                   if(op.getClientes().get(i).getNombre().equals(nombre) && op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo().equals(codigo)){
                       p=1;
                       if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).isTrabajoFinalizado()==false){
                        a=k;
                      
                       op.getClientes().get(i).getMecanico().get(j).aumentarHoras(a, numero);
//                       JOptionPane.showMessageDialog(null,"numero de horas ingresadas"+numero);
                       JOptionPane.showMessageDialog(null,"Numero de horas Que lleva el trabajo"+ op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getNumeroHora()) ;
                       VentanaPrincipal.archivo = false;
                       }
                       if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).isTrabajoFinalizado()==true){
                           JOptionPane.showMessageDialog(null," No puede aumentar mas Horas - TRABAJO FINALIZADO");
                       }
                    }
                   }
               }
           }
        if(p==0){
            JOptionPane.showMessageDialog(null,"Datos ingresados no validos","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
        txtNombreAumentar.setText("");
        txtCodigoAumentar.setText("");
        txtMatriculaAumentar.setText("");
        txtHorasAumentar.setText("");
        
        VentanaMecanico mecanico;
        mecanico = new VentanaMecanico(null,true);
        this.dispose();
        mecanico.setLocationRelativeTo(null);
        mecanico.setVisible(true);
        mecanico.setLocationRelativeTo(null);
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Debe ingresar un numero ","Advertencia",JOptionPane.WARNING_MESSAGE);
       }
//     Persistencia.escribirContacto(op);
    
         
    }//GEN-LAST:event_btnAumentarHorasActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        
        for(int i=0;i<op.getClientes().size();i++){
            for(int j=0;j<5;j++){
            
             if(j==0){ op.getClientes().get(i).setNombre((String)tablaClientes.getValueAt(i,j));}
             if(j==1) {op.getClientes().get(i).setIdentificacion((String)tablaClientes.getValueAt(i,j));}
             if(j==2){op.getClientes().get(i).setDireccion((String)tablaClientes.getValueAt(i,j));}  
             if(j==3) {op.getClientes().get(i).setTelefono((String)tablaClientes.getValueAt(i,j));}
             if(j==4) {op.getClientes().get(i).setCargo((String)tablaClientes.getValueAt(i,j));}
             if(j==5) {for(int k = 0; k<op.getClientes().get(i).getVehiculo().size(); k++){ op.getClientes().get(i).getVehiculo().get(k).setMatricula((String)tablaClientes.getValueAt(i,j));}}
                            
                              }
        }
//       Persistencia.escribirContacto(op);
      // llenarTabla();
       JOptionPane.showMessageDialog(null,"Se han guardado cambios");
       VentanaPrincipal.archivo = false;
       this.dispose();
       VentanaMecanico mecanico;
       mecanico = new VentanaMecanico(null,true);
       mecanico.setLocationRelativeTo(null);
       mecanico.setVisible(true);
      
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnAgregarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaterialesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        dialogoAgregarMaterial.setLocationRelativeTo(null);
        dialogoAgregarMaterial.setBounds(400, 300, 520,320);
        dialogoAgregarMaterial.setVisible(true);
     
    }//GEN-LAST:event_btnAgregarMaterialesActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        ///////// colocar bloques try catch
       try{
        ////////// DETALLES DE MATERIAL /////////////
        String nombre = txtnombreMa.getText();
        double precio = Double.parseDouble(txtPrecioMa.getText());
        int cantidad = Integer.parseInt(txtCantidadMa.getText());
        ////////// DETALLES DE MATERIAL /////////////
        
        //////// DETALLES DE PROVEEDOR ////////////
        nombreProv = txtNombreDelProveedor.getText();
        fax = txtFaxProveedor.getText();
        cod = txtCodigoProveedores.getText();
        pais = txtPaisProveedor.getText();
        Proveedores obj1 = new Proveedores(nombreProv, cod, fax, pais);
        //////// DETALLES DE PROVEEDOR ////////////
        Material obj = new Material(nombre,precio, cantidad);
        obj.agregarProveedor(obj1);
        op.agregarListaMateriales(obj);
          
        //Persistencia.escribirContacto(op);
//        JOptionPane.showMessageDialog(null,"nombre "+op.getMaterialesPredeterminados().get(0).getNombre()+" precio"
//        +op.getMaterialesPredeterminados().get(0).getPrecio()+" Cantidad "+op.getMaterialesPredeterminados().get(0).getCantidad()
//                +"\n --- Datos de los proveedores: Nombre: "+op.getMaterialesPredeterminados().get(0).getProveedores().get(0).getNombre());
        dialogoAgregarMaterial.dispose();
        VentanaPrincipal.archivo = false;
        llenarTabla2();
        txtnombreMa.setText("");
        txtPrecioMa.setText("");
        txtCantidadMa.setText("");
        txtNombreDelProveedor.setText("");
        txtFaxProveedor.setText("");
        txtCodigoProveedores.setText("");
        txtPaisProveedor.setText("");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Debe ingresar correctamente los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
       }
//       finally{
//           llenarTabla2();
//       }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMaterialActionPerformed
        // TODO add your handling code here:
         //// elimina un trabajo de la tabla de trabajos
        try{
        DefaultTableModel model = (DefaultTableModel) tablaMateriales.getModel();
        int a = tablaMateriales.getSelectedRow();
        model.removeRow(a);
        op.getMaterialesPredeterminados().remove(a);
       
        //Persistencia.escribirContacto(op);
        llenarTabla2();
        this.dispose();
        VentanaMecanico mecanico = new VentanaMecanico(null,true);
        mecanico.setLocationRelativeTo(null);
        mecanico.setVisible(true);
        VentanaPrincipal.archivo = false;
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"Advertencia","Debe seleccionar el campo que desea eliminar",JOptionPane.WARNING_MESSAGE);
        }finally{
            llenarTabla2();
        }
    }//GEN-LAST:event_btnEliminarMaterialActionPerformed

    private void btnGuardarCambiosMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMaterialesActionPerformed
        // TODO add your handling code here:
         for(int i=0;i<op.getMaterialesPredeterminados().size();i++){
            for(int j=0;j<3;j++){
            
             if(j==0){op.getMaterialesPredeterminados().get(i).setNombre((String)tablaMateriales.getValueAt(i,j));}
             if(j==1){
                 int x = Integer.parseInt((String)tablaMateriales.getValueAt(i,j));
                 op.getMaterialesPredeterminados().get(i).setCantidad(x);
             }
             if(j==2){
                 double x = Double.parseDouble((String)tablaMateriales.getValueAt(i,j));
                 op.getMaterialesPredeterminados().get(i).setPrecio(x);
             }  
             }
        }
//      Persistencia.escribirContacto(op);
      // llenarTabla();
       JOptionPane.showMessageDialog(null,"Se han guardado cambios");
       VentanaPrincipal.archivo = false;
       this.dispose();
        VentanaMecanico mecanico = new VentanaMecanico(null,true);
        mecanico.setLocationRelativeTo(null);
        mecanico.setVisible(true);
       
    }//GEN-LAST:event_btnGuardarCambiosMaterialesActionPerformed

    private void btnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaterialActionPerformed
        // TODO add your handling code here:
        
        try{
        int a = tablaMaterial.getSelectedRow();
         String nombre = op.getMaterialesPredeterminados().get(a).getNombre();
         double precio = op.getMaterialesPredeterminados().get(a).getPrecio();
         int cantidad = Integer.parseInt(txtCantidad.getText());
         
         String nombreCliente = txtNombreMaterial.getText();
         String matricula = txtMatriculaMaterial.getText();
         String codigo = txtCodigoMaterial.getText();
         int opc=0;
         
         if(op.getMaterialesPredeterminados().get(a).getCantidad()-cantidad>=0){
         String nom=""; String codig = ""; String fax1 = ""; String pais1 = "";
         for(int c = 0; c<op.getMaterialesPredeterminados().get(a).getProveedores().size(); c++){
             nom = op.getMaterialesPredeterminados().get(a).getProveedores().get(c).getNombre();
             codig = op.getMaterialesPredeterminados().get(a).getProveedores().get(c).getCodigo();
             fax1=op.getMaterialesPredeterminados().get(a).getProveedores().get(c).getFax(); 
             pais1 = op.getMaterialesPredeterminados().get(a).getProveedores().get(c).getPais();
         }
         
         for(int i=0; i<op.getClientes().size(); i++){
             for(int j=0; j<op.getClientes().get(i).getVehiculo().size(); j++){
                 if(op.getClientes().get(i).getNombre().equals(nombreCliente) && op.getClientes().get(i).getVehiculo().get(j).getMatricula().equals(matricula)){
                    
                     for(int l=0; l<op.getClientes().get(i).getMecanico().size(); l++){
                         
                         for(int k=0; k<op.getClientes().get(l).getMecanico().get(l).getTrabajos().size(); k++){
                           
                            if(op.getClientes().get(i).getMecanico().get(l).getTrabajos().get(k).isTrabajoFinalizado()==false && !op.getClientes().get(i).getMecanico().get(l).getTrabajos().get(k).getTipoTrabajo().equals("Revision")){
                             opc=1;
                             Proveedores ob = new Proveedores(nom, codig, fax1, pais1); 
                             Material obj = new Material(nombre,precio,cantidad);
                             obj.agregarProveedor(ob);
                             op.getClientes().get(i).getMecanico().get(l).agregarMaterial(k, obj);
                             op.getMaterialesPredeterminados().get(a).setCantidad(op.getMaterialesPredeterminados().get(a).getCantidad()-cantidad);
                             VentanaPrincipal.archivo = false;
                            }else{
                                if(op.getClientes().get(i).getMecanico().get(l).getTrabajos().get(k).isTrabajoFinalizado()==true){
                                opc=1;
                                JOptionPane.showMessageDialog(null,"No puede agregarse mas material -- TRABAJO FINALIZADO --");}
                                if(op.getClientes().get(i).getMecanico().get(l).getTrabajos().get(k).getTipoTrabajo().equals("Revision")){
                                opc=1;
                                JOptionPane.showMessageDialog(null,"Los trabajos de tipo revision no agregan material","Advertencia",JOptionPane.WARNING_MESSAGE);}
                            }
                        
                     }
                     }
                   
                 }
             }
         }
         }else{ opc = 1; JOptionPane.showMessageDialog(null,"El material se ha acabado - NO PUEDE AGREGAR MATERIAL -","Advertencia",JOptionPane.WARNING_MESSAGE);}
         if(opc==0){
             JOptionPane.showMessageDialog(null,"Datos ingresados invalidos","Advertencia",JOptionPane.ERROR_MESSAGE);
         }
//          Persistencia.escribirContacto(op);
         llenarTabla2(); 
         txtCantidad.setText("");
         txtNombreMaterial.setText("");
         txtMatriculaMaterial.setText("");
         txtCodigoMaterial.setText("");
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"No ha seleccionado el material a agregar");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"No ha ingresado los datos correctamente");
        }
        finally{
            llenarTabla2();
        }
       
    }//GEN-LAST:event_btnAgregarMaterialActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtHorasAumentarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasAumentarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHorasAumentarKeyTyped

    private void txtPrecioMaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioMaKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioMaKeyTyped

    private void txtCantidadMaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadMaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadMaKeyTyped

    private void btnAgregarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDiagnosticoActionPerformed
        // TODO add your handling code here:
        
        String codigo = txtCodigoDelTrabajo.getText();
        String matricula = txtMAtriculaDelVehiculo.getText(); 
        String nombre = txtNombredelCLiente.getText();
        String identificacion = txtIdentificacionCliente.getText();
        String diagnostico = textDiagnostico.getText();
        int opc = 0, f=0;
        if(!codigo.equals("") && !matricula.equals("") && !nombre.equals("") && !identificacion.equals("") && !diagnostico.equals("")){
        for(int i=0; i<op.getClientes().size(); i++){
            for(int j=0; j<op.getClientes().get(i).getMecanico().size(); j++){
                for(int k=0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size(); k++){
                    if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo().equals(codigo) && op.getClientes().get(i).getNombre().equals(nombre)
                                                        && op.getClientes().get(i).getIdentificacion().equals(identificacion)){
                        opc=1;
                        if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getTipoTrabajo().equals("Revision")){
                            f=1;
                            if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).isTrabajoFinalizado()==false){
                            op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).setDiagnostico(diagnostico);
                            System.out.println("Diagnostico "+op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getDiagnostico());
                            JOptionPane.showMessageDialog(null,"Diagnostico agregado con exito");
                       }else{ opc = 1; f=1;JOptionPane.showMessageDialog(null,"El trabajo se ha finalizado - NO SE PUEDE MODIFICAR DIAGNOSTICO -","Advertencia",JOptionPane.WARNING_MESSAGE);}
                    }
                   }
                }
            }
        }
        }else{ opc = 1; f=1;JOptionPane.showMessageDialog(null,"Debe llenar todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);}
        if(opc==0){
            JOptionPane.showMessageDialog(null,"Datos ingresados invalidos","Advertencia",JOptionPane.WARNING_MESSAGE);
            f=1;
        }
        if(f==0){
            JOptionPane.showMessageDialog(null,"El trabajo debe ser de tipo Revision","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarDiagnosticoActionPerformed
  
    public void llenarTabla(){
      
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
    
     for(int i=0;i<op.getClientes().size();i++){
        String nombre= op.getClientes().get(i).getNombre();
        String id= op.getClientes().get(i).getIdentificacion();
        String direccion= op.getClientes().get(i).getDireccion();
        String telefono= op.getClientes().get(i).getTelefono();
        String cargo = op.getClientes().get(i).getCargo();
        String matricula="";
       
        for(int j=0; j<op.getClientes().get(i).getVehiculo().size();j++){
            matricula = op.getClientes().get(i).getVehiculo().get(j).getMatricula();
           }
        
    String datos2[]={nombre,id,direccion,telefono,cargo,matricula};
    modelo.addRow(datos2);
    }
    }
   
   public void llenarTabla2(){
       while(modeloTabla2.getRowCount()>0)
            modeloTabla2.removeRow(0);
       
       while(modeloTabla3.getRowCount()>0)
           modeloTabla3.removeRow(0);
       
   for(int i=0;i<op.getMaterialesPredeterminados().size();i++){
      
        String nombre = op.getMaterialesPredeterminados().get(i).getNombre();
        int cant=  op.getMaterialesPredeterminados().get(i).getCantidad();
        double precio=  op.getMaterialesPredeterminados().get(i).getPrecio();
        

    String datos3[]={nombre,""+cant,""+precio};
    modeloTabla2.addRow(datos3);
    
    String datos4[] = {nombre,""+cant, ""+precio};
    modeloTabla3.addRow(datos4);
    }
   
   }
   public void llenarTabla4(){
       while(modeloTabla4.getRowCount()>0)
            modeloTabla4.removeRow(0);
       
       for(int i =0 ; i<op.getClientes().size(); i++){
           for(int j=0; j<op.getClientes().get(i).getMecanico().size(); j++){
               for(int k=0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size(); k++){
                    if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getTipoTrabajo().equals("Revision")){
                        String codigo = op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo();
                        String matricula = "";
                        String nombre = op.getClientes().get(i).getNombre();
                        String id = op.getClientes().get(i).getIdentificacion();
                        for(int l=0; l<op.getClientes().get(i).getVehiculo().size();l++){
                           matricula = op.getClientes().get(i).getVehiculo().get(l).getMatricula();
                    }
                   String datos5[] = {codigo,matricula,nombre,id};
                   modeloTabla4.addRow(datos5);
               }
             }
           }
           
       }
       
       
       
   }
   
   public void cerrar() {
        try {
            /*confirmacion de salida*/
            this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            addWindowListener( new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
         //   this.setVisible(true);//hacemos visible el frame
        }catch (Exception e) {
//            e.printStackTrace();
        }
    }
    
    public void confirmarSalida(){
//        int i =JOptionPane.showConfirmDialog(this,"¿Esta seguro de salir del programa?","Confirmar Salida",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
//        if(i==0){
//            ;
            this.dispose();
            VentanaMecanico mecanico = new VentanaMecanico(null,true);
            mecanico.setLocationRelativeTo(null);
            mecanico.setVisible(true);
            //System.exit(0);  
            
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaModificar dialog = new VentanaModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarDiagnostico;
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnAgregarMateriales;
    private javax.swing.JButton btnAumentarHoras;
    private javax.swing.JButton btnEliminarMaterial;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnGuardarCambiosMateriales;
    private javax.swing.JComboBox comboAccion;
    private javax.swing.JDialog dialogoAgregarMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel listaRevision;
    private javax.swing.JPanel panelAgregarMaterial;
    private javax.swing.JPanel panelAumentarHoras;
    private javax.swing.JPanel panelDiagnostico;
    private javax.swing.JPanel panelModificarDatos;
    private javax.swing.JPanel panelModificarTrabajo;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaMaterial;
    private javax.swing.JTable tablaMateriales;
    private javax.swing.JTable tablaTrabajosRevision;
    private javax.swing.JTextArea textDiagnostico;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadMa;
    private javax.swing.JTextField txtCodigoAumentar;
    private javax.swing.JTextField txtCodigoDelTrabajo;
    private javax.swing.JTextField txtCodigoMaterial;
    private javax.swing.JTextField txtCodigoProveedores;
    private javax.swing.JTextField txtFaxProveedor;
    private javax.swing.JTextField txtHorasAumentar;
    private javax.swing.JTextField txtIdentificacionCliente;
    private javax.swing.JTextField txtMAtriculaDelVehiculo;
    private javax.swing.JTextField txtMatriculaAumentar;
    private javax.swing.JTextField txtMatriculaMaterial;
    private javax.swing.JTextField txtNombreAumentar;
    private javax.swing.JTextField txtNombreDelProveedor;
    private javax.swing.JTextField txtNombreMaterial;
    private javax.swing.JTextField txtNombredelCLiente;
    private javax.swing.JTextField txtPaisProveedor;
    private javax.swing.JTextField txtPrecioMa;
    private javax.swing.JTextField txtnombreMa;
    // End of variables declaration//GEN-END:variables
}
