/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import static Vista.TallerDeMecanicaApp.op;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Astrid
 */
public class VentanaReportes extends javax.swing.JDialog {
 
    /////////////// PARA LA TABLA DE CLIENTES  ////////////////////////////////////////////
     String titulo[]={"Nombre","Identificacion","Telefono","Dirección","Correo","Ocupacion","Matricula del Vehiculo"};
     Object datos[][];
     DefaultTableModel modelo ;
      /////////////// PARA LA TABLA DE CLIENTES  ////////////////////////////////////////////
     
     //////////////// PARA LA TABLA DE TRABAJOS ///////////////////////////////////////
     String tituloTablaTrabajos[]={"Codigo del Trabajo","Matricula del Vehiculo","Fecha de ingreso","Numero de Horas Trabajadas","Plazo Maximo","Tipo de Trabajo","Valor en Piezas","Valor a Pagar"};
     Object datosTablaTrabajos[][];
     DefaultTableModel modeloTablaTrabajos;
     ////////////// PARA LA TABLA DE TRABAJOS //////////////////////////////////////
    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo =  new DefaultTableModel(datos,titulo);
        tablaClientes.setModel(modelo);
        
        modeloTablaTrabajos = new DefaultTableModel(datosTablaTrabajos,tituloTablaTrabajos);
        tablaTrabajos.setModel(modeloTablaTrabajos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentanaPrincipal = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelTrabajos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTrabajos = new javax.swing.JTable();
        panelClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        setResizable(false);

        btnVentanaPrincipal.setText("Aceptar");
        btnVentanaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPrincipalActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaTrabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaTrabajos);

        javax.swing.GroupLayout panelTrabajosLayout = new javax.swing.GroupLayout(panelTrabajos);
        panelTrabajos.setLayout(panelTrabajosLayout);
        panelTrabajosLayout.setHorizontalGroup(
            panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTrabajosLayout.setVerticalGroup(
            panelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Trabajos", panelTrabajos);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", panelClientes);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/66.png"))); // NOI18N
        jLabel2.setText("TALLER MECANICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPrincipalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnVentanaPrincipalActionPerformed

    public void llenarTablas(){
     ///////////// LIMPIAR LA TABLA DE CLIENTES   
     while(modelo.getRowCount()>0)
            modelo.removeRow(0);
    /////////////// LIMPIAR LA TABLA DE TRABAJOS
     while(modeloTablaTrabajos.getRowCount()>0)
         modeloTablaTrabajos.removeRow(0);
    
     //////////// LLENANDO LA TABLA DE CLIENTES //////////////////
     for(int i=0;i<op.getClientes().size();i++){
        String nombre= op.getClientes().get(i).getNombre();
        String id= op.getClientes().get(i).getIdentificacion();
        String direccion= op.getClientes().get(i).getDireccion();
        String telefono= op.getClientes().get(i).getTelefono();
        String correo = op.getClientes().get(i).getCorreo();
        String cargo = op.getClientes().get(i).getCargo();
        String matricula="";
        
        for(int j=0; j<op.getClientes().get(i).getVehiculo().size();j++){
            matricula = op.getClientes().get(i).getVehiculo().get(j).getMatricula();
           }
        
    String datos2[]={nombre,id,telefono,direccion,correo,cargo,matricula};
    modelo.addRow(datos2);
    }
     
    ////////////// LLENANDO LA TABLA DE TRABAJOS ///////////////////
     String matric = "";
     String piezas = "";
    for(int i = 0; i<op.getClientes().size(); i++){
         
        for(int j=0; j<op.getClientes().get(i).getMecanico().size(); j++){
            
            for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size(); k++){
                
                String codigo = op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo();
                int hora = op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getNumeroHora();
                int plazo = op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getPlazoMaximo();
                String tipo = op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getTipoTrabajo();
                double valor = op.getClientes().get(i).getMecanico().get(j).getValorPagar();
                    
               
                for(int h=0;h<op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getPiezas().size(); h++ ){
                   
                    piezas =""+op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getPrecioMaterial();
                }
               
                for(int l=0; l<op.getClientes().get(i).getVehiculo().size();l++){
                         matric = op.getClientes().get(i).getVehiculo().get(l).getMatricula();
                        }
                String fecha = op.getClientes().get(i).getMecanico().get(j).getFechaIngreso();
                String datos3[]={codigo,matric,fecha,""+hora,""+plazo/24+" dias",tipo,piezas,""+valor};
                modeloTablaTrabajos.addRow(datos3);
            }   
        }
    
    }
  
    }
    
    
   
     
     
//    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaReportes dialog = new VentanaReportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentanaPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelTrabajos;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaTrabajos;
    // End of variables declaration//GEN-END:variables
}
