/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Cliente;
import Logica.Material;
import Logica.Mecanico;
import Logica.Persistencia;
import Logica.Proveedores;

import Logica.TallerMecanico;
import Logica.Trabajo;
import Logica.Vehiculo;
import static Vista.TallerDeMecanicaApp.op;
import java.text.DateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Astrid
 */
public class VentanaNuevoCliente extends javax.swing.JDialog {
   
     /// cliente
    private String tipo, nombre, direccion, telefono, identificacion, correo, cargo; boolean descuento;
        /// contacto
    private String nombreContacto, cargocontacto, telefonoContacto, correoContacto, identificacionContacto;
    private String marca, modelo, anio,matricula,serial,clase,observaciones; /// datos del vehiculo
    private String fecha, tipoM, nombreM, telefonoM, identificacionM, correoM, tipoRep, seguroM, ob, nombreTrab; /// datos del trabajo
   
    DateFormat df = DateFormat.getDateInstance();
   
  
    /**
     * Creates new form VentanaNuevoCliente
     */
    public VentanaNuevoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
        modificarBotones();
        ///////////  variables globales a la clase que contienen los datos que ingresa el usuario  //////////
        tipo = ""; nombre=""; direccion=""; telefono=""; identificacion=""; correo=""; cargo=""; descuento = false;
        nombreContacto = ""; cargocontacto= ""; telefonoContacto=""; correoContacto="";  identificacionContacto="";
        marca = ""; modelo = ""; anio = ""; matricula = ""; serial = "";  clase = ""; observaciones = ""; /// vehiculo
        fecha =""; tipoM = ""; nombreM = ""; telefonoM = ""; identificacionM = ""; correoM = ""; tipoRep = ""; seguroM = ""; ob = ""; nombreTrab=""; /// trabajo
         ///////////  variables globales a la clase que contienen los datos que ingresa el usuario  //////////
        
        
        modificar(panelMecanicoJefe,false);
        btnReparar.setEnabled(false);
        btnRevisar.setEnabled(false);
        observacion.setEnabled(false);
        LabelTipo.setEnabled(false);
        tipoReparacion.setEnabled(false);
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void modificar(JPanel panel, boolean b) {
            panel.setEnabled(b);
            for (int i = 0; i < panel.getComponentCount(); i++) {
                panel.getComponent(i).setEnabled(b);
            }
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoVehiculo = new javax.swing.JDialog();
        panelPrincipal = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtClase = new javax.swing.JTextField();
        panelPropietario = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        btnListoVehiculo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        dialogoTrabajo = new javax.swing.JDialog();
        panel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tipoTrabajo = new javax.swing.JComboBox();
        panelMecanicoJefe = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNombreMecanico = new javax.swing.JTextField();
        txtIdentificacionMecanico = new javax.swing.JTextField();
        txtCorreoMecanico = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtSeguroMecanico = new javax.swing.JTextField();
        txtTelefonoMecanico = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtNombreTrabajo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        observacion = new javax.swing.JTextField();
        btnReparar = new javax.swing.JButton();
        btnRevisar = new javax.swing.JButton();
        LabelTipo = new javax.swing.JLabel();
        tipoReparacion = new javax.swing.JComboBox();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        panelClienteNuevo = new javax.swing.JPanel();
        tipoCliente = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cargoCliente = new javax.swing.JComboBox();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelContacto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombreContacto = new javax.swing.JTextField();
        txtTelefonoContacto = new javax.swing.JTextField();
        txtCorreoContacto = new javax.swing.JTextField();
        txtIdentificacionContacto = new javax.swing.JTextField();
        cargoContacto = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtObservacione = new javax.swing.JTextField();
        btnListo = new javax.swing.JButton();

        dialogoVehiculo.setTitle("Detalles de Vehiculo");
        dialogoVehiculo.setAlwaysOnTop(true);
        dialogoVehiculo.setResizable(false);

        panelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel18.setText("Matricula");

        jLabel19.setText("Marca");

        jLabel20.setText("Año");

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        jLabel21.setText("Modelo");

        jLabel22.setText("Serial");

        jLabel23.setText("Clase");

        panelPropietario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel25.setText("Identificacion");

        jLabel26.setText("Nombre");

        jLabel41.setText("Telefono");

        javax.swing.GroupLayout panelPropietarioLayout = new javax.swing.GroupLayout(panelPropietario);
        panelPropietario.setLayout(panelPropietarioLayout);
        panelPropietarioLayout.setHorizontalGroup(
            panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPropietarioLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelPropietarioLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8))))
        );
        panelPropietarioLayout.setVerticalGroup(
            panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 204));
        jLabel24.setText("Datos del Cliente (Propietario)");

        jLabel27.setText("Observaciones");

        btnListoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listo.png"))); // NOI18N
        btnListoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtAnio))))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMarca))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModelo))
                            .addComponent(txtSerial)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtClase))
                    .addComponent(panelPropietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtObservaciones)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Datos del Vehiculo");

        javax.swing.GroupLayout dialogoVehiculoLayout = new javax.swing.GroupLayout(dialogoVehiculo.getContentPane());
        dialogoVehiculo.getContentPane().setLayout(dialogoVehiculoLayout);
        dialogoVehiculoLayout.setHorizontalGroup(
            dialogoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dialogoVehiculoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        dialogoVehiculoLayout.setVerticalGroup(
            dialogoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoVehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dialogoTrabajo.setTitle("Detalles de Mecanico");
        dialogoTrabajo.setResizable(false);

        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel28.setText("Fecha de Ingreso");

        jLabel29.setText("Tipo de Trabajo");

        tipoTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Revision", "Reparacion", " " }));
        tipoTrabajo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoTrabajoItemStateChanged(evt);
            }
        });

        panelMecanicoJefe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel31.setText("Nombre");

        jLabel32.setText("Identificacion");

        jLabel33.setText("Correo");

        txtNombreMecanico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreMecanicoKeyTyped(evt);
            }
        });

        txtIdentificacionMecanico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionMecanicoKeyTyped(evt);
            }
        });

        jLabel35.setText("N° Seguro Social");

        jLabel36.setText("Telefono");

        txtTelefonoMecanico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoMecanicoKeyTyped(evt);
            }
        });

        jLabel34.setText("Nombre del Trabajo");

        javax.swing.GroupLayout panelMecanicoJefeLayout = new javax.swing.GroupLayout(panelMecanicoJefe);
        panelMecanicoJefe.setLayout(panelMecanicoJefeLayout);
        panelMecanicoJefeLayout.setHorizontalGroup(
            panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(32, 32, 32)
                        .addComponent(txtNombreMecanico))
                    .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                        .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreoMecanico, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtIdentificacionMecanico))
                        .addGap(18, 18, 18)
                        .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSeguroMecanico, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(32, 32, 32)
                                .addComponent(txtTelefonoMecanico))))
                    .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreTrabajo)))
                .addContainerGap())
        );
        panelMecanicoJefeLayout.setVerticalGroup(
            panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMecanicoJefeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtNombreMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtIdentificacionMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txtSeguroMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtCorreoMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(txtTelefonoMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMecanicoJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtNombreTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel30.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 204));
        jLabel30.setText("Mecanico Jefe");

        jLabel39.setText("Observaciones:");

        btnReparar.setText("Reparar");
        btnReparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepararActionPerformed(evt);
            }
        });

        btnRevisar.setText("Revisar");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });

        LabelTipo.setText("Tipo de reparacion: ");

        tipoReparacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Latoneria", "Mecanico" }));

        jdcFecha.setMinSelectableDate(new Date());

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReparar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRevisar))
                    .addComponent(panelMecanicoJefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(observacion)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(tipoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(LabelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addGap(2, 2, 2)
                .addComponent(panelMecanicoJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipo)
                    .addComponent(tipoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReparar)
                        .addComponent(btnRevisar))
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoTrabajoLayout = new javax.swing.GroupLayout(dialogoTrabajo.getContentPane());
        dialogoTrabajo.getContentPane().setLayout(dialogoTrabajoLayout);
        dialogoTrabajoLayout.setHorizontalGroup(
            dialogoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogoTrabajoLayout.setVerticalGroup(
            dialogoTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresa cliente");
        setResizable(false);

        panelClienteNuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        tipoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Particular", "Empresa" }));

        jLabel2.setText("Tipo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Direccion");

        jLabel5.setText("Telefono");

        jLabel6.setText("Correo");

        jLabel7.setText("Cargo");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        cargoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estudiante", "Independiente", "Empleado" }));

        jLabel8.setText("Identificacion");

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelClienteNuevoLayout = new javax.swing.GroupLayout(panelClienteNuevo);
        panelClienteNuevo.setLayout(panelClienteNuevoLayout);
        panelClienteNuevoLayout.setHorizontalGroup(
            panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                        .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(11, 11, 11)
                                .addComponent(txtTelefono))
                            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tipoCliente, 0, 181, Short.MAX_VALUE)
                                    .addComponent(txtNombre)))
                            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(txtDireccion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(8, 8, 8)
                                .addComponent(cargoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteNuevoLayout.setVerticalGroup(
            panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Cliente");

        panelContacto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel10.setText("Nombre");

        jLabel11.setText("Cargo");

        jLabel12.setText("Telefono");

        jLabel13.setText("Correo");

        jLabel14.setText("Identificacion");

        txtNombreContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreContactoKeyTyped(evt);
            }
        });

        txtTelefonoContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoContactoKeyTyped(evt);
            }
        });

        txtIdentificacionContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionContactoKeyTyped(evt);
            }
        });

        cargoContacto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Independiente", "Empleado" }));

        javax.swing.GroupLayout panelContactoLayout = new javax.swing.GroupLayout(panelContacto);
        panelContacto.setLayout(panelContactoLayout);
        panelContactoLayout.setHorizontalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoContacto))
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreContacto)
                            .addComponent(cargoContacto, 0, 196, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(36, 36, 36)
                        .addComponent(txtCorreoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentificacionContacto)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelContactoLayout.setVerticalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(txtNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(txtIdentificacionContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Contacto");

        jLabel16.setText("Observaciones: ");

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listo.png"))); // NOI18N
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtObservacione)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListo))
                    .addComponent(panelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelClienteNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelClienteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListo)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacione, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
       
        ///// Capturando los datos ingresados del cliente /////
        tipo = tipoCliente.getSelectedItem().toString();
        nombre = txtNombre.getText();
        direccion = txtDireccion.getText();
        telefono = txtTelefono.getText();
        identificacion = txtIdentificacion.getText();
        correo = txtCorreo.getText();
        cargo = cargoCliente.getSelectedItem().toString();
        nombreContacto = txtNombreContacto.getText();
        cargocontacto = cargoContacto.getSelectedItem().toString();
        telefonoContacto = txtTelefonoContacto.getText();
        correoContacto = txtCorreoContacto.getText();
        identificacionContacto = txtIdentificacionContacto.getText();
        ///// Capturando los datos de los clientes /////
        if(!tipo.equals("") && !nombre.equals("") && !direccion.equals("") && !telefono.equals("") && !identificacion.equals("") && !correo.equals("") && !cargo.equals("") && !nombreContacto.equals("") 
                         && !cargoContacto.equals("Seleccione") && !telefonoContacto.equals("") && !correoContacto.equals("") && !identificacionContacto.equals("")){
        this.dispose();
        dialogoVehiculo.setLocationRelativeTo(null);  
        dialogoVehiculo.setBounds(470, 180, 454,410);
        dialogoVehiculo.setVisible(true);
  
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar Todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnListoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoVehiculoActionPerformed
        // TODO add your handling code here:
       ////// CAPTURANDO LOS DATOS DEL VEHICULO  ///// 
        marca = txtMarca.getText();
        modelo = txtModelo.getText();
        anio = txtAnio.getText();
        matricula = txtMatricula.getText();
        serial = txtSerial.getText();
        clase = txtClase.getText();
        observaciones = txtObservaciones.getText();
           ////// CAPTURANDO LOS DATOS DEL VEHICULO  ///// 
        
        if(!marca.equals("") && !modelo.equals("") && !anio.equals("") && !matricula.equals("") && !serial.equals("") && !clase.equals("")){
        dialogoTrabajo.setLocationRelativeTo(null);
        dialogoVehiculo.dispose();
        dialogoTrabajo.setBounds(390,100,540,420);
        dialogoTrabajo.setVisible(true);
        //dialogoTrabajo.setLocationRelativeTo(null);
        
     //   Vehiculo op = new Vehiculo (marca,modelo,anio,matricula,serial,clase,observaciones);
     //   obj3.agregarVehiculo(op);
        }else{
            JOptionPane.showMessageDialog(dialogoVehiculo,"Debe llenar Todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnListoVehiculoActionPerformed

    private void tipoTrabajoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoTrabajoItemStateChanged
        // TODO add your handling code here:
        if(tipoTrabajo.getSelectedItem().toString().equals("Revision")){
             modificar(panelMecanicoJefe,true);
             btnRevisar.setEnabled(true);
             observacion.setEnabled(true);
             btnReparar.setEnabled(false);
             LabelTipo.setEnabled(false);
             tipoReparacion.setEnabled(false);
             observacion.setEnabled(true);
        }
        if(tipoTrabajo.getSelectedItem().toString().equals("Reparacion")){
             modificar(panelMecanicoJefe,true);
             btnReparar.setEnabled(true);
             btnRevisar.setEnabled(false);
             observacion.setEnabled(true);
             LabelTipo.setEnabled(true);
             tipoReparacion.setEnabled(true);
            }
    }//GEN-LAST:event_tipoTrabajoItemStateChanged

   
    private void btnRepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepararActionPerformed
        // TODO add your handling code here:
        try{   
        ////  ///// capturando los datos del trabajo / mecanico
        fecha =  df.format(jdcFecha.getDate());
        System.out.println("La fecha "+ fecha);
        tipoM = tipoTrabajo.getSelectedItem().toString();
        nombreM = txtNombreMecanico.getText();
        telefonoM = txtTelefonoMecanico.getText();
        identificacionM = txtIdentificacionMecanico.getText();
        correoM = txtCorreoMecanico.getText();
        seguroM = txtSeguroMecanico.getText();
        ob = observacion.getText();
        tipoRep = tipoReparacion.getSelectedItem().toString();
        nombreTrab = txtNombreTrabajo.getText();
         ///// capturando los datos del trabajo / mecanico
        
        if(!fecha.equals("")&& !tipoM.equals("") && !nombreM.equals("Seleccine") && !telefonoM.equals("") && !identificacionM.equals("") && !correoM.equals("") && !seguroM.equals("") && !tipoRep.equals("Seleccione") && !nombreTrab.equals("")){
        //// datos del trabajo ///
        String codigo="";
        int numeroHora=0, plazo=0;
        double precio = 0;
        boolean finalizado=false;
        if(tipoRep.equals("Latoneria")){
            codigo = matricula+"-33";  /// generando el codigo de trabajo de acuerdo a la matricula del vehiculo y al tipo de trabajo
            numeroHora = 0; plazo = 21*24;  /// al principio el numero de horas es 0 el plazo maximo a lo que corresponde (trabajo)
            precio=0;
            finalizado = false;     /// Al principio el trabajo finalizado es falso ya que aun no se han agregado horas...
       }
       
        if(tipoRep.equals("Mecanico")){
            codigo = matricula+"-44";  /// generando el codigo de trabajo de acuerdo a la matricula del vehiculo y al tipo de trabajo
            numeroHora = 0; plazo = 14*24;  /// al principio el numero de horas es 0 el plazo maximo a lo que corresponde (trabajo)
            precio=0;
            finalizado = false;     /// Al principio el trabajo finalizado es falso ya que aun no se han agregado horas...
        }
        //// datos del trabajo /////
        
        
        //// datos del material y proveedores ////  como por el momento no se ha ingresado nada solo se dejara en 0 todo
        String nombrePieza = "";
        double precioPieza = 0;
        int cantidad = 0;
        
//        String nombreProv = ""; String fax = ""; String cod = ""; String pais= "";
//        Proveedores o = new Proveedores ( nombreProv, cod, fax, pais);
        //// datos del material ////  como por el momento no se ha ingresado nada solo se dejara en 0 todo
        
        
        Material piezas = new Material(nombrePieza,precioPieza,cantidad); /// se crea un objeto de la clase material que hara parte del primer cliente ingresado
//        piezas.agregarProveedor(o);
        Trabajo ob1 = new Trabajo();
      /////
              
       /////// dando los valores que ingresaron a cada variable de trabajo  /////
            ob1.setCodigo(codigo);
            ob1.setNumeroHora(numeroHora);
            ob1.setPlazoMaximo(plazo);
            ob1.setTrabajoFinalizado(finalizado);
            ob1.setPrecioMaterial(precio);
            ob1.setTipoTrabajo(tipoRep);
            ob1.setDiagnostico("");
            ob1.setNombreTrabajo(nombreTrab);
        /////// dando los valores que ingresaron a cada variable de trabajo  /////
            ob1.agregarMaterial(piezas);   /// aca 
         //// GUARDANDO LOS DATOS DEL VEHICULO - MECANICO - CLIENTE ////////
         
        Vehiculo ob2 = new Vehiculo(marca,modelo,anio,matricula,clase,serial,observaciones);   /// instanciando el objeto de vehiculo
        Mecanico ob3 = new Mecanico();
         /////// dando los valores que ingresaron a cada variable de MEcanico  /////
        ob3.setNombreMecanico(nombreM);
        ob3.setCorreoMecanico(correoM);
        ob3.setFechaIngreso(fecha);
        ob3.setIdentificacionMecanico(identificacionM);
        ob3.setObservacion(ob);
        ob3.setSeguroMecanico(seguroM);
        ob3.setTelefonoMecanico(telefonoM);
        ob3.setValorPagar(0);
        /////// dando los valores que ingresaron a cada variable de MEcanico  /////
        ob3.agregarTrabajo(ob1);
      
        Cliente obj = new Cliente();
        /////// dando los valores que ingresaron a cada variable de Cliente  /////
        obj.setNombre(nombre);
        obj.setCargo(cargo);
        obj.setCorreo(correo);
        obj.setIdentificacion(identificacion);
        obj.setDireccion(direccion);
        obj.setTelefono(telefono);
        obj.setTipo(tipo);
        obj.setCargoContacto(cargocontacto);
        obj.setCorreoContacto(correoContacto);
        obj.setIdentificacionContacto(identificacionContacto);
        obj.setTelefonoContacto(telefonoContacto);
        obj.setNombreContacto(nombreContacto);
        
        /////// dando los valores que ingresaron a cada variable de Cliente  /////
        obj.agregarVehiculo(ob2, ob3);
        op.agregarCliente(obj);  //// se agrega al taller de mecanica los clientes que se ingresan
        
//        ///// Forma adecuada para trabajar con las arraylist que contiene cada cliente - mecanico - trabajo
       System.out.println(op.getClientes().size());
//        for(int i=0; i<op.getClientes().size(); i++){
//        JOptionPane.showMessageDialog(null,"nombre del cliente "+op.getClientes().get(i).getNombre());
//                  for(int j=0; j<op.getClientes().get(i).getMecanico().size();j++){
//                      JOptionPane.showMessageDialog(null,"\n Nombre del Mecanico"+op.getClientes().get(i).getMecanico().get(j).getNombreMecanico());
//                      for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size(); k++){
//                           JOptionPane.showMessageDialog(null,"\n Codigo Trabajo "+op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo());
//                      }         
//                  }
//                  for(int g=0; g<op.getClientes().get(i).getVehiculo().size();g++){
//                   JOptionPane.showMessageDialog(null,"matricula del vehiculo "+op.getClientes().get(i).getVehiculo().get(g).getMatricula());
//                  }
//        }
        
         JOptionPane.showMessageDialog(null,"Nuevo trabajo agregado con exito"
                    +"\nEl codigo del trabajo es: "+codigo);
        VentanaPrincipal.archivo = false;
        dialogoTrabajo.dispose();
        
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtIdentificacion.setText("");
        txtCorreo.setText("");
        txtNombreContacto.setText("");
        txtTelefonoContacto.setText("");
        txtCorreoContacto.setText("");
        txtIdentificacionContacto.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtAnio.setText("");
        txtMatricula.setText("");
        txtSerial.setText("");
        txtClase.setText("");
        txtObservaciones.setText("");
        txtNombreMecanico.setText("");
        txtTelefonoMecanico.setText("");
        txtIdentificacionMecanico.setText("");
        txtCorreoMecanico.setText("");
        txtSeguroMecanico.setText("");
        observacion.setText("");
        txtNombreTrabajo.setText("");
        
        VentanaMecanico mecanico = new VentanaMecanico(null,true);
        mecanico.setLocationRelativeTo(null);
        mecanico.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar Todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"Debe llenar Todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"Proceso Invalido","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRepararActionPerformed

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        // TODO add your handling code here:
        
        try{
        ////  ///// capturando los datos del trabajo / mecanico
        fecha =  df.format(jdcFecha.getDate());
        tipoM = tipoTrabajo.getSelectedItem().toString();
        nombreM = txtNombreMecanico.getText();
        telefonoM = txtTelefonoMecanico.getText();
        identificacionM = txtIdentificacionMecanico.getText();
        correoM = txtCorreoMecanico.getText();
        seguroM = txtSeguroMecanico.getText();
        ob = observacion.getText();
        
         ///// capturando los datos del trabajo / mecanico
        
       if( !tipoM.equals("") && !nombreM.equals("") && !telefonoM.equals("") && !identificacionM.equals("") && !correoM.equals("") && !seguroM.equals("") ){
        //// datos del material ////  como por el momento no se ha ingresado nada solo se dejara en 0 todo
        String nombrePieza = "";
        double precioPieza = 0;
        int cantidad = 0;
//         String nombreProv = ""; String fax = ""; String cod = ""; String pais= "";
//        Proveedores o = new Proveedores ( nombreProv, cod, fax, pais);
        //// datos del material ////  como por el momento no se ha ingresado nada solo se dejara en 0 todo
        
        Material piezas = new Material(nombrePieza,precioPieza,cantidad); /// se crea un objeto de la clase material que hara parte del primer cliente ingresado
//        piezas.agregarProveedor(o);
        
        //// datos del trabajo ///
        String codigo = matricula+"-10";  /// generarlo de manera aleatoria....
        int numeroHora = 0, plazo = 7*24;  /// al principio el numero de horas es 0 el plazo maximo ---DEFINIR ----
        double precio=0;
        boolean finalizado = false;     /// Al principio el trabajo finalizado es falso ya que aun no se han agregado horas...
        //// datos del trabajo /////
        
        
        Trabajo ob1 = new Trabajo();
        nombreTrab = txtNombreTrabajo.getText();      
        /////// dando los valores que ingresaron a cada variable de trabajo  /////
        ob1.setCodigo(codigo);
        ob1.setNumeroHora(numeroHora);
        ob1.setPlazoMaximo(plazo);
        ob1.setTrabajoFinalizado(finalizado);
        ob1.setPrecioMaterial(precio);
        ob1.setTipoTrabajo("Revision");
        ob1.setDiagnostico("");
        ob1.setNombreTrabajo(nombreTrab);
        /////// dando los valores que ingresaron a cada variable de trabajo  /////
        ob1.agregarMaterial(piezas);  
        
        
         
        Vehiculo ob2 = new Vehiculo(marca,modelo,anio,matricula,clase,serial,observaciones);   /// instanciando el objeto de vehiculo
        Mecanico ob3 = new Mecanico();
         /////// dando los valores que ingresaron a cada variable de MEcanico  /////
        ob3.setNombreMecanico(nombreM);
        ob3.setCorreoMecanico(correoM);
        ob3.setFechaIngreso(fecha);
        ob3.setIdentificacionMecanico(identificacionM);
        ob3.setObservacion(ob);
        ob3.setSeguroMecanico(seguroM);
        ob3.setTelefonoMecanico(telefonoM);
        ob3.setValorPagar(0);
         /////// dando los valores que ingresaron a cada variable de MEcanico  /////
        ob3.agregarTrabajo(ob1);
      
        Cliente obj = new Cliente();
        /////// dando los valores que ingresaron a cada variable de Cliente  /////
        obj.setNombre(nombre);
        obj.setCargo(cargo);
        obj.setCorreo(correo);
        obj.setIdentificacion(identificacion);
        obj.setDireccion(direccion);
        obj.setTelefono(telefono);
        obj.setTipo(tipo);
        obj.setCargoContacto(cargocontacto);
        obj.setCorreoContacto(correoContacto);
        obj.setIdentificacionContacto(identificacionContacto);
        obj.setTelefonoContacto(telefonoContacto);
        obj.setNombreContacto(nombreContacto);
        /////// dando los valores que ingresaron a cada variable de Cliente  /////
        obj.agregarVehiculo(ob2, ob3);
        op.agregarCliente(obj);  //// se agrega al taller de mecanica los clientes que se ingresan
        
//        ///// Forma adecuada para trabajar con las arraylist que contiene cada cliente - mecanico - trabajo
       System.out.println(op.getClientes().size());
//        for(int i=0; i<op.getClientes().size(); i++){
//        JOptionPane.showMessageDialog(null,"nombre del cliente "+op.getClientes().get(i).getNombre());
//                  for(int j=0; j<op.getClientes().get(i).getMecanico().size();j++){
//                      JOptionPane.showMessageDialog(null,"\n Nombre del Mecanico"+op.getClientes().get(i).getMecanico().get(j).getNombreMecanico());
//                      for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size(); k++){
//                           JOptionPane.showMessageDialog(null,"\n Codigo Trabajo "+op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo());
//                      }         
//                  }
//                  for(int g=0; g<op.getClientes().get(i).getVehiculo().size();g++){
//                   JOptionPane.showMessageDialog(null,"matricula del vehiculo "+op.getClientes().get(i).getVehiculo().get(g).getMatricula());
//                  }
//        }
//        Persistencia.escribirContacto(op);
        JOptionPane.showMessageDialog(null,"Nuevo trabajo agregado con exito"
                    +"\nEl codigo del trabajo es: "+codigo); 
        VentanaPrincipal.archivo = false;
        dialogoTrabajo.dispose();
        
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtIdentificacion.setText("");
        txtCorreo.setText("");
        txtNombreContacto.setText("");
        txtTelefonoContacto.setText("");
        txtCorreoContacto.setText("");
        txtIdentificacionContacto.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtAnio.setText("");
        txtMatricula.setText("");
        txtSerial.setText("");
        txtClase.setText("");
        txtObservaciones.setText("");
        txtNombreMecanico.setText("");
        txtTelefonoMecanico.setText("");
        txtIdentificacionMecanico.setText("");
        txtCorreoMecanico.setText("");
        txtSeguroMecanico.setText("");
        observacion.setText("");
        txtNombreTrabajo.setText("");
        
        VentanaMecanico mecanico = new VentanaMecanico(null,true);
        mecanico.setLocationRelativeTo(null);
        mecanico.setVisible(true);
        }else{
          JOptionPane.showMessageDialog(null,"Debe llenar Todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
       }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"Debe llenar Todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRevisarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ') {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtNombreContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreContactoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreContactoKeyTyped

    private void txtIdentificacionContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionContactoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacionContactoKeyTyped

    private void txtTelefonoContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoContactoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoContactoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreMecanicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMecanicoKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreMecanicoKeyTyped

    private void txtIdentificacionMecanicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionMecanicoKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacionMecanicoKeyTyped

    private void txtTelefonoMecanicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoMecanicoKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoMecanicoKeyTyped

    public void modificarBotones(){
        btnListoVehiculo.setBorderPainted(false);
        btnListoVehiculo.setContentAreaFilled(false);
        btnListo.setBorderPainted(false);
        btnListo.setContentAreaFilled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaNuevoCliente dialog = new VentanaNuevoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnListoVehiculo;
    private javax.swing.JButton btnReparar;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JComboBox cargoCliente;
    private javax.swing.JComboBox cargoContacto;
    private javax.swing.JDialog dialogoTrabajo;
    private javax.swing.JDialog dialogoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField observacion;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelClienteNuevo;
    private javax.swing.JPanel panelContacto;
    private javax.swing.JPanel panelMecanicoJefe;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPropietario;
    private javax.swing.JComboBox tipoCliente;
    private javax.swing.JComboBox tipoReparacion;
    private javax.swing.JComboBox tipoTrabajo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtClase;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoContacto;
    private javax.swing.JTextField txtCorreoMecanico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIdentificacionContacto;
    private javax.swing.JTextField txtIdentificacionMecanico;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreContacto;
    private javax.swing.JTextField txtNombreMecanico;
    private javax.swing.JTextField txtNombreTrabajo;
    private javax.swing.JTextField txtObservacione;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtSeguroMecanico;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoContacto;
    private javax.swing.JTextField txtTelefonoMecanico;
    // End of variables declaration//GEN-END:variables
}
