/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Latoneria;
import Logica.Mecanico;
import Logica.Persistencia;
import static Vista.TallerDeMecanicaApp.op;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.StringTokenizer;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Astrid
 */
public class VentanaMecanico extends javax.swing.JDialog {
    VentanaNuevoCliente cliente;
    VentanaModificar mod;
    VentanaConsultar consulta;
    VentanaEliminar elimina;
    VentanaDetallesMecanico mec;
    private boolean archivo;
  
   
    /**
     * Creates new form VentanaMecanico
     */
    public VentanaMecanico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cliente = new VentanaNuevoCliente(null,true);
        cliente.setLocationRelativeTo(null);
        mod = new VentanaModificar(null,true);
        mod.setLocationRelativeTo(null);
        consulta = new VentanaConsultar(null,true);
        consulta.setLocationRelativeTo(null);
        elimina = new VentanaEliminar(null,true);
        elimina.setLocationRelativeTo(null);
        mec = new VentanaDetallesMecanico(null,true);
        mec.setLocationRelativeTo(null);
        mod.llenarTabla();
        mod.llenarTabla2();
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoTrabajo = new javax.swing.JButton();
        btnModificarTrabajo = new javax.swing.JButton();
        btnEliminarTrabajo = new javax.swing.JButton();
        btnFinalizarTrabajo = new javax.swing.JButton();
        btnBuscarTrabajo = new javax.swing.JButton();
        btnConsultarPlazo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de trabajos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoTrabajo.setText("Nuevo Trabajo");
        btnNuevoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 36));

        btnModificarTrabajo.setText("Modificar Trabajo");
        btnModificarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 36));

        btnEliminarTrabajo.setText("Eliminar Trabajo");
        btnEliminarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 36));

        btnFinalizarTrabajo.setText("Finalizar Trabajo");
        btnFinalizarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 35));

        btnBuscarTrabajo.setText("Buscar Trabajo");
        btnBuscarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 170, 36));

        btnConsultarPlazo.setText("Consultar Plazo Maximo");
        btnConsultarPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPlazoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarPlazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dientes-engranajes-azules-1584021.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTrabajoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnNuevoTrabajoActionPerformed

    private void btnModificarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTrabajoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mod.llenarTabla();
        mod.llenarTabla2();
        mod.llenarTabla4();
        mod.setVisible(true);
    }//GEN-LAST:event_btnModificarTrabajoActionPerformed

    private void btnBuscarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTrabajoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        String id =JOptionPane.showInputDialog(null,"Ingrese la cedula o matricula del vehiculo del trabajo que desea Buscar");
        boolean o = consulta.buscar(id);
        if(o==true){
            consulta.llenarTabla(id);
            consulta.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Proceso invalido");
        }
        
        
    }//GEN-LAST:event_btnBuscarTrabajoActionPerformed

    private void btnEliminarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTrabajoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        elimina.llenarTablas();
        elimina.setVisible(true);
       
    }//GEN-LAST:event_btnEliminarTrabajoActionPerformed

    private void btnFinalizarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarTrabajoActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(null,"Ingrese el codigo del trabajo que desea Finalizar");
        int a=0;
        int opc = 0;
        int f=0; 
        for(int i=0; i<op.getClientes().size(); i++){
            for(int j=0; j<op.getClientes().get(i).getMecanico().size();j++){
                for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size();k++){
                   
                    if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo().equals(codigo)){
                        opc=1;
                       if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).isTrabajoFinalizado()==false){
                        f=1;
                        if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getNumeroHora()>0 && op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getPrecioMaterial()>0 || (op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getTipoTrabajo().equals("Revision") && !op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getDiagnostico().equals("") && op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getNumeroHora()>0)){
                        
                        a=k;
                        op.getClientes().get(i).getMecanico().get(j).finalizarTrabajo(a);
                         JOptionPane.showMessageDialog(null,"Trabajo Finalizado Correctamente");
                        op.getClientes().get(i).calcularManoObra(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getTipoTrabajo(),j,op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getPrecioMaterial(),op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getNumeroHora());
                        JOptionPane.showMessageDialog(null,"el valor a pagar es: "+op.getClientes().get(i).getMecanico().get(j).getValorPagar());
                         VentanaPrincipal.archivo = false;
                        }else{
                                if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getTipoTrabajo().equals("Revision")){
                                    JOptionPane.showMessageDialog(null,"No ha agregado Diagnostico al trabajo o no ha ingresado horas de trabajo","Advertencia",JOptionPane.WARNING_MESSAGE);
                                }else{
                                opc=1; JOptionPane.showMessageDialog(null,"No ha agregado material o no ha ingresado horas de trabajo","Advertencia",JOptionPane.WARNING_MESSAGE);}
                   
                       }
                 }
                }
            }
        }
        }
        if(opc==0){
            JOptionPane.showMessageDialog(null,"Proceso no valido","Advertencia",JOptionPane.ERROR_MESSAGE);
            f=1;
        }
        if(f==0){
            JOptionPane.showMessageDialog(null,"El trabajo ya ha sido finalizado");
        }
        
        
//       Persistencia.escribirContacto(op);
      /// AL FINALIZAR EL TRABAJO SE CALCULA EL COSTO DE MANO DE OBRA ////////////
        
    }//GEN-LAST:event_btnFinalizarTrabajoActionPerformed

    private void btnConsultarPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPlazoActionPerformed
        // TODO add your handling code here:}
        int opc=0;
        String id = JOptionPane.showInputDialog(null,"ingrese el numero de identificacion del cliente o la matricula del vehiculo");
        for(int i=0; i<op.getClientes().size(); i++){
            for(int j=0; j<op.getClientes().get(i).getVehiculo().size();j++){
                if(op.getClientes().get(i).getIdentificacion().equals(id) || op.getClientes().get(i).getVehiculo().get(j).getMatricula().equals(id)){
                    opc=1;
                    
                    for(int l =0; l<op.getClientes().get(i).getMecanico().size(); l++){
                        for(int k = 0; k<op.getClientes().get(i).getMecanico().get(l).getTrabajos().size(); k++){
                            if(op.getClientes().get(i).getMecanico().get(l).getTrabajos().get(k).isTrabajoFinalizado()==false){
                            JOptionPane.showMessageDialog(null,"El plazo maximo del trabajo: "+op.getClientes().get(i).getMecanico().get(l).getTrabajos().get(k).getPlazoMaximo()/24+" Dias "+
                            "\nA nombre de la persona: "+op.getClientes().get(i).getNombre());
                        }else{  JOptionPane.showMessageDialog(null,"Ya se ha finalizado trabajo","Advertencia",JOptionPane.WARNING_MESSAGE);}
                       }
                    }
                }
            }
        }
        if(opc==0){
           JOptionPane.showMessageDialog(null,"Numero de identificacion o matricula invalidos","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarPlazoActionPerformed

     public void cerrar() {
        try {
            /*confirmacion de salida*/
            this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            addWindowListener( new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
         //   this.setVisible(true);//hacemos visible el frame
        }catch (Exception e) {
//            e.printStackTrace();
        }
    }
    
    public void confirmarSalida(){
//        int i =JOptionPane.showConfirmDialog(this,"¿Esta seguro de salir del programa?","Confirmar Salida",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
//        if(i==0){
//            ;
          
          mod.llenarTabla();
          mod.llenarTabla2();
            //System.exit(0);  
            
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaMecanico dialog = new VentanaMecanico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTrabajo;
    private javax.swing.JButton btnConsultarPlazo;
    private javax.swing.JButton btnEliminarTrabajo;
    private javax.swing.JButton btnFinalizarTrabajo;
    private javax.swing.JButton btnModificarTrabajo;
    private javax.swing.JButton btnNuevoTrabajo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
