/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import static Vista.TallerDeMecanicaApp.op;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Astrid
 */
public class VentanaFacturacion extends javax.swing.JDialog {
      
    /**
     * Creates new form VentanaFacturacion
     */
    public VentanaFacturacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modificar(panelPago,true);
        modificar(panelCambio,false);
        btnAplicarDescuento.setEnabled(false);
        
        
    }

    public void modificar(JPanel panel, boolean b) {
            panel.setEnabled(b);
            for (int i = 0; i < panel.getComponentCount(); i++) {
                panel.getComponent(i).setEnabled(b);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPago = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificacionCliente = new javax.swing.JTextField();
        btnAceptarPago = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtValorCancelar = new javax.swing.JTextField();
        panelCambio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtValorTrabajo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codigoDelTrabajo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        btnAplicarDescuento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        panelPago.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Datos del Cliente a Facturar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel2.setText("Nombre");

        jLabel1.setText("Identificacion");

        btnAceptarPago.setText("Aceptar Pago");
        btnAceptarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPagoActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor a Cancelar");

        txtValorCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorCancelarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelPagoLayout = new javax.swing.GroupLayout(panelPago);
        panelPago.setLayout(panelPagoLayout);
        panelPagoLayout.setHorizontalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPagoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorCancelar))
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentificacionCliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptarPago)))
                .addContainerGap())
        );
        panelPagoLayout.setVerticalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarPago))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCambio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Detalles de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel4.setText("Valor del trabajo");

        jLabel5.setText("Codigo del Trabajo");

        jLabel7.setText("Se le debe entregar al Cliente");

        javax.swing.GroupLayout panelCambioLayout = new javax.swing.GroupLayout(panelCambio);
        panelCambio.setLayout(panelCambioLayout);
        panelCambioLayout.setHorizontalGroup(
            panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelCambioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoDelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(panelCambioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCambioLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCambio)))
                .addContainerGap())
        );
        panelCambioLayout.setVerticalGroup(
            panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(codigoDelTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAplicarDescuento.setText("Aplicar Descuento");
        btnAplicarDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarDescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCambio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAplicarDescuento)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAplicarDescuento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarDescuentoActionPerformed
        // TODO add your handling code here:
         String nombre = txtNombreCliente.getText();
         String id = txtIdentificacionCliente.getText();
         double valor = Double.parseDouble(txtValorCancelar.getText());
        int p = 0;
        for(int i=0; i<op.getClientes().size(); i++){
           for(int j=0; j<op.getClientes().get(i).getMecanico().size(); j++){
                if(op.getClientes().get(i).getNombre().equals(nombre) && op.getClientes().get(i).getIdentificacion().equals(id)){
                    p=1;
               for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size();k++){
                if(op.getClientes().get(i).isDescuento()==false){
                 if(valor>=op.getClientes().get(i).getMecanico().get(j).getValorPagar()){
                    op.aplicarDescuento(valor, i);
                    modificar(panelCambio,true);
                    btnAplicarDescuento.setEnabled(true);
                    txtValorTrabajo.setText(""+op.getClientes().get(i).getMecanico().get(j).getValorPagar());
                    codigoDelTrabajo.setText(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo());
                    this.cambio(valor, op.getClientes().get(i).getMecanico().get(j).getValorPagar());
                    op.getClientes().get(i).setPago(true);
                  
               }else{JOptionPane.showMessageDialog(null,"El valor ingresado no abarca el pago al trabajo","Advertencia",JOptionPane.WARNING_MESSAGE);}
             
            }else{
                JOptionPane.showMessageDialog(null,"Ya se ha aplicado el descuento a este cliente","Error",JOptionPane.ERROR_MESSAGE);
            }
           }
           }
        }
     }
        
       
        if(p==0){
            JOptionPane.showMessageDialog(null,"Proceso no valido","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAplicarDescuentoActionPerformed

    private void btnAceptarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPagoActionPerformed
        // TODO add your handling code here:
        try{
        String nombre = txtNombreCliente.getText();
         String id = txtIdentificacionCliente.getText();
         double valor = Double.parseDouble(txtValorCancelar.getText());
         int p=0;
        if(!nombre.equals("") && !id.equals("")) {
           
            for(int i=0; i<op.getClientes().size(); i++){
                for(int j=0; j<op.getClientes().get(i).getMecanico().size();j++){
                    
                    if(op.getClientes().get(i).getNombre().equals(nombre) && op.getClientes().get(i).getIdentificacion().equals(id)){
                        p=1;
                        for(int k = 0; k<op.getClientes().get(i).getMecanico().get(j).getTrabajos().size();k++){
                        if(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).isTrabajoFinalizado()==true){
                        if(valor>=op.getClientes().get(i).getMecanico().get(j).getValorPagar()){
                        if(op.getClientes().get(i).isPago()==false){
                            modificar(panelCambio,true);
                            btnAplicarDescuento.setEnabled(true);
                            txtValorTrabajo.setText(""+op.getClientes().get(i).getMecanico().get(j).getValorPagar());
                            codigoDelTrabajo.setText(op.getClientes().get(i).getMecanico().get(j).getTrabajos().get(k).getCodigo());
                            this.cambio(valor, op.getClientes().get(i).getMecanico().get(j).getValorPagar());
                            op.getClientes().get(i).setPago(true);
                    }else{JOptionPane.showMessageDialog(null,"Este Trabajo ya fue Cancelado","Advertencia",JOptionPane.WARNING_MESSAGE);}
                }else{JOptionPane.showMessageDialog(null,"El valor ingresado no abarca el pago al trabajo","Advertencia",JOptionPane.WARNING_MESSAGE);}
            }else{ JOptionPane.showMessageDialog(null,"No ha finalizado el trabajo","Advertencia",JOptionPane.WARNING_MESSAGE);}
            }
           }       
         }
        }
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        if(p==0){
            JOptionPane.showMessageDialog(null,"Proceso invalido","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
//        txtValorTrabajo.setText("");
//        txtIdentificacionCliente.setText("");
//        txtValorCancelar.setText((""));
//        txtNombreCliente.setText("");
//        codigoDelTrabajo.setText("");
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Debe ingresar un numero","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarPagoActionPerformed

    private void txtValorCancelarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCancelarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorCancelarKeyTyped

    public void cambio(double n, double a){
        double cambio = n-a;
        txtCambio.setText(""+cambio);
          
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaFacturacion dialog = new VentanaFacturacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPago;
    private javax.swing.JButton btnAplicarDescuento;
    private javax.swing.JTextField codigoDelTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelCambio;
    private javax.swing.JPanel panelPago;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtIdentificacionCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtValorCancelar;
    private javax.swing.JTextField txtValorTrabajo;
    // End of variables declaration//GEN-END:variables
}
